alias lsa='ls -a'
alias gotogit='cd ~/git'
alias showcommands='compgen -c | sort'
alias showaliases='compgen -a | sort'
alias gpuon='tee /proc/acpi/bbswitch <<<OFF'
alias gpuoff='tee /proc/acpi/bbswitch <<<ON'
