alias ls='ls --color=auto'
alias lsa='ls -a --color=auto'
alias showcommands='compgen -c | sort'
alias showaliases='compgen -a | sort'
alias gpuoff='sudo tee /proc/acpi/bbswitch <<<OFF'
alias gpuon='sudo tee /proc/acpi/bbswitch <<<ON'
alias getpublicip='curl icanhazip.com'
